global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ERAIF Emergency Connector
  - job_name: 'eraif-emergency-connector'
    static_configs:
      - targets: ['eraif:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 15s
    
  # PostgreSQL metrics (if using PostgreSQL)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    
  # DICOM metrics (custom exporter)
  - job_name: 'dicom-exporter'
    static_configs:
      - targets: ['eraif:8081']
    metrics_path: '/dicom/metrics'
    scrape_interval: 30s
    
  # Emergency system metrics
  - job_name: 'emergency-systems'
    static_configs:
      - targets: ['eraif:8080']
    metrics_path: '/emergency/metrics'
    scrape_interval: 5s  # More frequent for emergency monitoring
    
  # Healthcare integration metrics
  - job_name: 'healthcare-integrations'
    static_configs:
      - targets: ['eraif:8080']
    metrics_path: '/integrations/metrics'
    scrape_interval: 20s
